# Copyright (c) 2023 Golioth, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Build firmware images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Artifact Version.'
        required: true
        default: 'v0.0.0'
        type: string
    
  workflow_call:
    inputs:
      version:
        description: 'Artifact Version.'
        required: true
        default: 'v0.0.0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    container: golioth/golioth-zephyr-base@sha256:22c46cf271b0a293110d95556a656ee3a204cdb364088c5f415f58fd1f52118a

    steps:
      - name: Setup West workspace
        run: |
          west init -m https://github.com/$GITHUB_REPOSITORY .
          west update --narrow -o=--depth=1
          west zephyr-export
          pip3 install -r deps/zephyr/scripts/requirements-base.txt
          west blobs fetch hal_espressif

      - name: Troubleshooting
        run: |
          ls ~/.cmake/packages/

      # - name: Build with West
      #   run: |
      #     west build -p -b esp32_devkitc_wrover app/ -- -DCONFIG_GOLIOTH_SAMPLE_FW_VERSION=\"${{ inputs.version }}\"

      # - name: Prepare artifacts
      #   run: |
      #     mv build/zephyr/zephyr.bin build/zephyr/golioth_${{ inputs.version }}.bin

      # # Run IDs are unique per repo but are reused on re-runs
      # - name: Save artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build_artifacts_${{ github.run_id }}
      #     path: |
      #       build/zephyr/golioth_${{ inputs.version }}.bin